chore: if epoch is missing, log which one
ethereum/trin pull request #1546
Opened 2024-10-22 21:31 UTC by carver

### What was wrong?

### How was it fixed?

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

2024-10-22 21:45 UTC, KolbyML approved these changes
I am assuming this change is to make it so the error is clearer

2024-10-23 03:53 UTC, carver commented
Yeah exactly. Sorry I didn't have a PR description before.

You can now see in the test output that epoch 701 is missing:
```
thread 'utils::tests::test_get_era_file_download_links' panicked at e2store/src/utils.rs:98:59:
called `Result::unwrap()` on an `Err` value: Epoch indices are not starting from zero or not consecutive: missing epoch 701
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test utils::tests::test_get_era_file_download_links ... FAILED
```

2024-10-23 04:27 UTC, carver commented
Getting this ready to go. If it's not fixed by tomorrow, let's turn master green again.

2024-10-23 04:32 UTC, KolbyML reviewed
> Getting this ready to go. If it's not fixed by tomorrow, let's turn master green again.

Nobody is going to see a warning in CI, so I think we might as well remove the test in that case. I guess I will add a panic in Trin Execution as well

2024-10-23 05:24 UTC, KolbyML requested changes
I made a PR https://github.com/ethereum/trin/pull/1547 to remove the tests. If there is a problem with having tests which download from HTTP servers that is fine. We can remove the tests but removing the ensure!() here is not ok, because then Trin Execution will start with an era_files list which is incomplete which isn't ok. This check was added to ensure `get_era_files()` always return a valid sequential list with no files missing. Hence replacing this `ensure!()` with an warning isn't ok.

2024-10-23 05:24 UTC, KolbyML commented on e2store/src/utils.rs
> +            warn!("Epoch indices are not starting from zero or not consecutive: missing epoch {epoch_num}");
This shouldn't be a warning. This code is used elsewhere. It isn't only for the CI. It ensures whoever calls this function gets a complete sequential era_file list, the warning would be unexpected behavior from a user's perspective.

2024-10-23 05:25 UTC, KolbyML commented
I am going to set up our own mirror as well with the help of Paul

2024-10-24 03:46 UTC, carver commented
Yup, I'm happy to close in favor of #1547

2024-10-24 03:46 UTC, closed without merging