feat: add find content query pool to overlay
ethereum/trin pull request #352
Opened 2022-06-23 18:47 UTC by jacobkaufmann

### What was wrong?

The overlay does not support find content queries (i.e. lookups).

### How was it fixed?

Here we take a first step toward support for find content queries. We add a find content query pool field to `OverlayService`. This query pool is polled in the main loop, and the generated query events are handled.

At this stage, no queries are initialized, and there is no external API to initialize a find content query from outside the overlay. Content found by a query is not republished to other nodes who did not possess the content. These pieces of functionality will be added in subsequent PRs.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [x] Clean up commit history

2022-06-29 17:04 UTC, mrferris requested changes
Looks great!

Only main thing is that I'd expect `find_enr` to need to look through both query pools in case it can't find an ENR in the routing table.

2022-06-30 05:15 UTC, jacobkaufmann commented on trin-core/src/portalnet/overlay_service.rs
> +                    if let Err(_) = callback.send(content) {
[crate docs](https://docs.rs/tokio/1.19.2/tokio/sync/oneshot/struct.Sender.html#method.send): "An unsuccessful send would be one where the corresponding receiver has already been deallocated."

To your point, I don't think the actual error message would add much information here.

2022-06-30 05:16 UTC, jacobkaufmann commented on trin-core/src/portalnet/overlay_service.rs
> +        for (query_info, _) in self.find_node_query_pool.iter() {
Yes, good catch!

2022-06-30 05:27 UTC, jacobkaufmann commented on trin-core/src/portalnet/overlay_service.rs
> +                find_content_query_pool: QueryPool::new(Duration::from_secs(60)),
We should be. Good callout.

2022-07-01 00:07 UTC, mrferris approved these changes
Looks good to merge!

2022-07-01 16:01 UTC, merged