Test windows unit tests
ethereum/trin pull request #404
Opened 2022-08-08 20:21 UTC by mrferris

### What was wrong?

This is a branch of #403, which runs windows unit tests, which fail

### How was it fixed?

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [ ] Clean up commit history

2022-08-09 23:34 UTC, carver commented
> instead of assigning it to a variable and explicitly calling close on it later.

Do you understand any more about *why* this is failing? I would love to know.

2022-08-09 23:50 UTC, carver approved these changes
👍🏻 for merging this one rather than worrying about updating #403

2022-08-10 07:29 UTC, ogenev approved these changes
Good job, let's merge this :+1:.

2022-08-10 08:11 UTC, ogenev commented
I think this is also a good opportunity to update CircleCI orbs version from `windows@2.2.0` to `windows@5.0.0`.

2022-08-10 17:01 UTC, jacobkaufmann commented
@carver as far as I can tell, this change makes it so that we do not rely on `tempfile` at all.

```rust
setup_temp_dir();
```

My understanding: This will construct a `TempDir` and run its destructor immediately, removing the directory. This function call, however, will [set the env var](https://github.com/ethereum/trin/blob/c07fce832ce735faa346d932d996833869cf9b9b/trin-core/src/utils/db.rs#L19) for the data directory. Later, when we [set up RocksDB](https://github.com/ethereum/trin/blob/c07fce832ce735faa346d932d996833869cf9b9b/trin-core/src/portalnet/storage.rs#L452), we will [create the data directory](https://github.com/ethereum/trin/blob/c07fce832ce735faa346d932d996833869cf9b9b/trin-core/src/utils/db.rs#L24-L34) at the path of the [previously set env var](https://github.com/ethereum/trin/blob/c07fce832ce735faa346d932d996833869cf9b9b/trin-core/src/utils/db.rs#L40) via `fs::create_dir_all`.

So it seems that we create permanent directories with this change. Either we were using the `tempfile` crate incorrectly, or there was a problem with our data directory path for Windows, or something else.

I'm happy that we make the fix, but I don't think this is the fix that we think it is. We should restructure how we set up the data directories and databases to remove the side effects apparent in the functions linked above.

2022-08-10 17:27 UTC, mrferris commented
@carver @jacobkaufmann's right, this usage leaves `TempDir`s lying about (for a minute I was wondering why it seemed to still be cleaning up...but they were just hidden files 🤦‍♂️)  which is what using `TempDir` is meant to avoid. So looks like we found a leaky usage of it in the peertest that happens to avoid the root issue of sqlite not playing nicely with `TempDir` holding that directory open at the same time.

2022-08-10 19:03 UTC, ogenev requested changes
Hmm, now I'm not sure if this is the fix as @jacobkaufmann mentioned. By removing the `rempdir` handle in tests on calling `setup_temp_dir`, we don't keep it in the scope anymore and then we can't delete the dir explicitly with `temp_dir.close()`.

One note on the `--ephemeral` flag: 
The way it is implemented, it is not expected to clean the directories right after Trin closes. Why is that? I think as a user, we may still want to look into DB after termination. The main thing that `--ephemeral` does is to create a new path on every run in OS's temp fodler. This way we guarantee that we always start with a clean database and we don't pollute the default Trin path, but we don't delete the directories automatically. 

The problem with `--ephemeral` is that it uses the same `setup_temp_dir` function and the usage of the `tempdir` crate there is redundant in this specific case (we still want to use tempdir in tests, so we can pass the ownership to the main test scope and close the dir with `close`).

Regarding the issue that we are trying to fix here, I think we have to find out why those tests pass on linux and not on windows.

2022-08-10 19:07 UTC, ogenev commented on trin-core/src/portalnet/storage.rs
> -        let temp_dir = setup_temp_dir();
This removal will not keep `temp_dir` in the current scope and `temp_dir` will go out of scope when `setup_temp_dir` finishes.

2022-08-10 23:50 UTC, carver commented
> One note on the `--ephemeral` flag:
> The way it is implemented, it is not expected to clean the directories right after Trin closes. Why is that? I think as a user, we may still want to look into DB after termination. The main thing that `--ephemeral` does is to create a new path on every run in OS's temp folder. This way we guarantee that we always start with a clean database and we don't pollute the default Trin path, but we don't delete the directories automatically.

Oh this is a big surprise to me. The word `ephemeral` strongly suggests that everything from the run will be gone when it's done running. The only counter-example I could think of is if it is run on top of an existing DB, in which case the changes might persist. But to be consistent with the meaning of the word ephemeral, it would also be totally reasonable to *refuse* to start on top of an existing DB.

It's not clear whether we should *rename* the flag to be something else (something like `--fresh-start`, because the current mechanics of the flag are valuable... or if we should modify the mechanics to match the name. That's a product question, and one I don't feel strongly about because I'm not using the flag myself either way. I usually want more control over things like port number, etc, than the flag would give me.

2022-08-11 08:11 UTC, ogenev commented
> Oh this is a big surprise to me. The word `ephemeral` strongly suggests that everything from the run will be gone when it's done running.

Yeah, maybe `ephemeral` is not the perfect word for this functionality but we are putting all the data into `/tmp` folder which [purpose](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s18.html) is to not persist the data.

Lighthouse also uses `tmp` folder to store temporariry data and I thought it is a better decision than trying to explicitly delete all folders after termination, I can't come with a use case that would require exactly this.

2022-08-11 19:08 UTC, mrferris commented
> I think as a user, we may still want to look into DB after termination.

I can see wanting that as a developer, for example for debugging DB operations, but what's a scenario in which a user would want to look at the raw data their now-destroyed node had collected?

I think that there's a large if not complete overlap between a.) people who want to, for example, keep peertest data around so that they can inspect it after the peertest completes and b.) people who know how to modify one line in the peertest source to make it not ephemeral anymore.

Whereas I can't think of any overlap of people who would want to inspect the data of an ephemeral node after it's gone and people who can't make that modification locally themselves.

2022-08-26 21:20 UTC, mrferris commented
@carver @ogenev What do you think of this approach? It fulfills both 1.) the files to be deleted automatically and 2.) allows the tests to pass on windows. Using a closure `{    }` to let the rocksdb and sqlite files go out of scope and clean themselves up before closing the `TempDir` is convenient, but I'm wondering whether you think it's an anti-pattern, or just awkward. If so I can write a method to explicity clean up the rocksdb and sqlite resources so that `TempDir` works.

2022-08-29 08:01 UTC, ogenev commented
> Using a closure `{ }` to let the rocksdb and sqlite files go out of scope and clean themselves up before closing the `TempDir` is convenient, but I'm wondering whether you think it's an anti-pattern, or just awkward. If so I can write a method to explicity clean up the rocksdb and sqlite resources so that `TempDir` works.

There is a method in the standard library for this: [drop](https://doc.rust-lang.org/std/mem/fn.drop.html). We can use it to explicitly drop the resources.

2022-08-31 20:19 UTC, mrferris commented on .circleci/config.yml
> +  win: circleci/windows@2.2.0
I'm going to fix the commit history to remove the upgrade/downgrade, and then do the upgrade in a separate PR. The upgrade breaks with current CI config.

2022-08-31 21:52 UTC, carver approved these changes
Yeah, the `drop()` solution seems good to me!

I still think we can remove most of the windows run commands, as done here:
https://github.com/ethereum/trin/pull/411/commits/0cdf253d0460a13f4d11d1bb58f54d705302d27d

So then the config.yml change would just be adding the `--workspace` to the `cargo test`... line and not adding all the clippy and build lines.

2022-08-31 21:53 UTC, carver commented
Surely this is out of draft status by now, right? 😆

2022-08-31 22:08 UTC, mrferris commented
> I still think we can remove most of the windows run commands
@carver Good catch, I hadn't intended to revert that.

2022-09-01 08:49 UTC, ogenev approved these changes
LGTM :100:

2022-09-01 14:49 UTC, merged