fix: address clippy errors
ethereum/trin pull request #412
Opened 2022-08-17 16:24 UTC by jacobkaufmann

### What was wrong?

`clippy` throws new errors, perhaps after #396.

### How was it fixed?

Fix `clippy` errors based on suggestions.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [ ] Clean up commit history

2022-08-17 17:38 UTC, ogenev approved these changes
:+1:

2022-08-18 06:21 UTC, ogenev requested changes
Blocking this until we decide what to do with the offer/accept test.

2022-08-18 17:27 UTC, njgheorghita commented
maybe we could just merge in the updated clippy fixes and move the offer/accept test change to a separate pr?

2022-08-18 20:35 UTC, ogenev approved these changes

2022-08-18 21:20 UTC, merged