Extract validation logic into trin-validation
ethereum/trin pull request #598
Opened 2023-03-17 16:01 UTC by njgheorghita

### What was wrong?
- `trin_core::types::validation::HeaderOracle` -> `trin_validation::oracle::HeaderOracle`
- `trin_core::types::validation::Validator` -> `trin_validation::validator::Validator`
- `trin_core::types::accumulator::MasterAccumulator` -> `trin_validation::accumulator::MasterAccumulator`
- consolidated `ethportal_api::OverlayContentKey` & `trin_core::..::OverlayContentKey` definitions into `ethportal_api::content_key::OverlayContentKey` definition

blocked by #593 

### How was it fixed?
- [x] move associated test assets

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [x] Clean up commit history

2023-03-20 19:10 UTC, njgheorghita commented
@ogenev w/ regards to the question of whether we keep `ethportal-api` standalone or not... imo, for the sake of moving forward let's ignore that question for this particular pr - since it's not the primary focus of this pr. We'll continue the discussion, and we can move types back into `ethportal-api` in a future pr if that's the course we decide upon

2023-03-21 15:08 UTC, ogenev requested changes

2023-03-21 15:08 UTC, ogenev commented on ethportal-api/src/types/content_key.rs
I don't understand why we want to remove those types from `ethportal-api`. Those are  already used in Glados for example [here](https://github.com/pipermerriam/glados/blob/8ad0255c78ceffdd91ecc8a30c1f237efd916df6/glados-core/src/jsonrpc.rs#L13) and [here](https://github.com/pipermerriam/glados/blob/8ad0255c78ceffdd91ecc8a30c1f237efd916df6/glados-audit/src/lib.rs#L9). Having them in `ethportal-api` is critical for the external usage of the library.

2023-03-21 15:53 UTC, njgheorghita commented on ethportal-api/src/types/content_key.rs
True, but we could just as easily re-export them in `ethportal-api` to be used in `glados` if they're defined inside `trin-types`. Either way... I've updated this pr, so that content keys are defined inside `ethportal-api` and I moved `Request` to `trin-types`. It honestly doesn't seem to make much of a difference so I'm probably being pedantic here but it just makes so much more sense to me to define all of our types inside `trin-types`....

2023-03-21 15:55 UTC, njgheorghita commented on ethportal-api/src/types/content_key.rs
It seems the issue at debate here is whether or not we want to maintain the current definition for the `trin-types` crate. (from its readme).
```
Library for shared types across trin workspace members. Types only used by a single workspace member belong in a root-level types module.
```

2023-03-22 05:14 UTC, carver approved these changes
No objection 👌🏻

2023-03-22 10:08 UTC, ogenev commented on ethportal-api/src/types/content_key.rs
> +pub struct IdentityContentKey {
I don't think we want to support and expose this struct to the library users of `ethportal-api`. If I get this right, `IdentityContentKey` is used only for testing in Trin and it is not part of portal network specs and the global protocol.

As long as `ethportal-api` expose the `OverlayContentKey` trait, any user has all the tools to create its own internal content key structs (for testing or etc).

I would move this type to `trin-types` crate, some for the `RawContentKey` type above.

2023-03-22 10:08 UTC, ogenev commented on ethportal-api/src/types/content_key.rs
> +pub struct IdentityContentKey {
I don't think we want to support and expose this struct to the library users of `ethportal-api`. If I get this right, `IdentityContentKey` is used only for testing in Trin and it is not part of portal network specs and the global protocol.

As long as `ethportal-api` expose the `OverlayContentKey` trait, any user has all the tools to create its own internal content key structs (for testing and etc).

I would move this type to `trin-types` crate, same for the `RawContentKey` type above.

2023-03-22 17:22 UTC, njgheorghita commented on ethportal-api/src/endpoints.rs
No worries, I missed this one. I have no problem moving more types into `trin-types` 😅

2023-03-23 08:22 UTC, ogenev approved these changes
Looks good! :+1:  :boat:

2023-03-23 13:14 UTC, merged