Finish implementing API endpoints for discv5/history for jsonrpsee
ethereum/trin pull request #683
Opened 2023-04-20 22:41 UTC by KolbyML

### What was wrong?

### How was it fixed?

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [ ] Clean up commit history

2023-04-21 21:46 UTC, KolbyML commented
I can rebase them into 1 comment. I tried to get it to detect the discv5_rpc was a rename in the first comment it shows it but when you view the PR's second comment it still shows that discv5 was destroyed and _rpc is brand new which I am not sure why. Especially since locally I don't have that issue so maybe it is a github detection issue? I am not sure why.

2023-04-23 09:43 UTC, ogenev commented on rpc/src/discv5.rs
Let's do it in a separate PR if we want to rename this file. Including this here makes tracking the changes in the file harder and we want to minimize the reviewer's overheat.

2023-04-24 05:35 UTC, KolbyML commented on rpc/src/discv5.rs
Resolved

2023-04-24 13:12 UTC, njgheorghita requested changes
Tests for all of these endpoints should be added to `ethportal-peertest/src/scenarios/basic.rs`

2024-03-09 08:34 UTC, KolbyML commented
Closing this as it is stale and not that high of a priority here is a issue with for https://github.com/ethereum/trin/issues/689 if someone wants to fix it in the future

2024-03-09 08:34 UTC, closed without merging